#!/usr/bin/env python3
"""../builds/psistorm-PMAC-NN.json -> psistorm_build_NN.h (the per-build parameter header psistorm.c includes)."""
import json, sys, os
here = os.path.dirname(os.path.abspath(__file__))
builds = os.path.join(here, '..', 'builds')
for nn in ['%02d' % i for i in range(20)]:
    b = json.load(open(f'{builds}/psistorm-PMAC-{nn}.json'))
    rows = ',\n'.join('    {%2d, 0x%02x, %s, %2d}' % (s['word'], s['tt'], s['k'] + 'u', s['rot']) for s in b['steps'])
    open(f'{here}/psistorm_build_{nn}.h', 'w').write(
        f'/* generated by gen_headers.py from builds/psistorm-PMAC-{nn}.json */\n'
        f'#define PS_NN {int(nn)}\n'
        f'#define PS_INIT {{ {", ".join(x + "u" for x in b["init"])} }}\n'
        f'#define PS_ROT_C {b["rot_c"]}\n'
        f'/* {{ message word, boolean-function truth table, constant, rotation }}; steps 0-79 are the first line, 80-159 the second */\n'
        f'#define PS_STEPS \\\n{{ \\\n' + ' \\\n'.join(r + ',' for r in rows.split(',\n')) + ' \\\n}\n')
print('wrote 20 headers')
